export const data = [
    {
        id: 1,
        image_url: './images/products/products-1.jpg',
        name: '11inch Macbook Air',
        category: 'Electronics',
        date_listed: '26th September',
        description: 'This is a very slick macbook pro that can serve so many purpose',
        rating: 4
    },
    {
        id: 2,
        image_url: './images/products/products-2.jpg',
        name: 'Full Study Table Combo',
        category: 'Furnitures',
        date_listed: '26th December',
        description: 'This is a table that can be used to study full time!',
        rating: 3
    },
    {
        id: 3,
        image_url: './images/products/products-3.jpg',
        name: '11inch Macbook Air',
        category: 'Electronics',
        date_listed: '26th June',
        description: 'This is a very slick macbook pro that can serve so many purpose',
        rating: 4
    },
    {
        id: 4,
        image_url: './images/products/products-4.jpg',
        name: 'Full Study Table Combo',
        category: 'Furnitures',
        date_listed: '26th December',
        description: 'This is a tabele that can be used to study full time!',
        rating: 2
    },
    {
        id: 5,
        image_url: './images/products/products-3.jpg',
        name: '11inch Macbook Air',
        category: 'Electronics',
        date_listed: '26th June',
        description: 'This is a very slick macbook pro that can serve so many purpose',
        rating: 4
    },
    {
        id: 6,
        image_url: './images/products/products-4.jpg',
        name: 'Full Study Table Combo',
        category: 'Furnitures',
        date_listed: '26th December',
        description: 'This is a tabele that can be used to study full time!',
        rating: 2
    }
]

export const category_list = [
    {
        id: 1,
        icon: 'fa-desktop',
        name: 'electronics',
        items: [
            {name: 'laptop', count: 93},
            {name: 'iphone', count: 223},
            {name: 'microsoft', count: 188},
            {name: 'monitors', count: 14}
        ]
    },
    {
        id: 2,
        icon: 'fa-apple',
        name: 'restaurants',
        items: [
            {name: 'cafe', count: 23},
            {name: 'fast food', count: 93},
            {name: 'restaurants', count: 80},
            {name: 'food track', count: 49}
        ]
    },{
        id: 3,
        icon: 'fa-home',
        name: 'real estate',
        items: [
            {name: 'farms', count: 33},
            {name: 'gym', count: 93},
            {name: 'hospitals', count: 78},
            {name: 'parlours', count: 20}
        ]
    },{
        id: 4,
        icon: 'fa-shopping-basket',
        name: 'shoppings',
        items: [
            {name: 'mens wears', count: 16},
            {name: 'accessories', count: 52},
            {name: 'kids wears', count: 98},
            {name: 'it & software', count: 34}
        ]
    },{
        id: 5,
        icon: 'fa-briefcase',
        name: 'jobs',
        items: [
            {name: 'it jobs', count: 10},
            {name: 'cleaning and washing', count: 53},
            {name: 'management', count: 28},
            {name: 'voluntary works', count: 44}
        ]
    },{
        id: 6,
        icon: 'fa-car',
        name: 'vehicles',
        items: [
            {name: 'bus', count: 2},
            {name: 'cars', count: 29},
            {name: 'motorbikes', count: 30},
            {name: 'rent car', count: 4}
        ]
    },{
        id: 7,
        icon: 'fa-paw',
        name: 'pets',
        items: [
            {name: 'cats', count: 65},
            {name: 'dogs', count: 23},
            {name: 'bird', count: 18},
            {name: 'others', count: 0}
        ]
    },{
        id: 8,
        icon: 'fa-laptop',
        name: 'services',
        items: [
            {name: 'cleaning', count: 344},
            {name: 'car washing', count: 93},
            {name: 'clothing', count: 8},
            {name: 'business', count: 12}
        ]
    }
]

export const feedbackData = [
    {
        icon: 'fa-smile-o',
        category: 'Happy Sellers',
        value: 407
    },
    {
        icon: 'fa-user-o',
        category: 'Active Members',
        value: 200
    },
    {
        icon: 'fa-bookmark-o',
        category: 'Verified Ads',
        value: 126
    },
    {
        icon: 'fa-smile-o',
        category: 'Happy Buyers',
        value: 84
    }
]

export const adsData = {
    my_ads: [
        {
            id: 1,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 2,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 3,
            image: './images/products/products-2.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 4,
            image: './images/products/products-4.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'rejected',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 5,
            image: './images/products/products-1.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 6,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 7,
            image: './images/products/products-2.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 8,
            image: './images/products/products-4.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'rejected',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 9,
            image: './images/products/products-1.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 10,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 11,
            image: './images/products/products-2.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 12,
            image: './images/products/products-4.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'rejected',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 13,
            image: './images/products/products-1.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        }
    ],

    favourite_ads: [
        {
            id: 1,
            image: './images/products/products-1.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Nigeria',
            category: 'laptop',
        },
        {
            id: 2,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 3,
            image: './images/products/products-2.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 4,
            image: './images/products/products-4.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'rejected',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 5,
            image: './images/products/products-1.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 6,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 7,
            image: './images/products/products-2.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 8,
            image: './images/products/products-4.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'rejected',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 9,
            image: './images/products/products-1.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 10,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 11,
            image: './images/products/products-2.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        }
    ],

    archived_ads: [
        {
            id: 2,
            image: './images/products/products-2.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 3,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 4,
            image: './images/products/products-4.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'rejected',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 5,
            image: './images/products/products-1.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 6,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 7,
            image: './images/products/products-2.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 8,
            image: './images/products/products-4.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'rejected',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 9,
            image: './images/products/products-1.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 10,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 11,
            image: './images/products/products-2.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        }
        ],

    pending_ads: [
        {
            id: 2,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 3,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 4,
            image: './images/products/products-4.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'rejected',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 5,
            image: './images/products/products-1.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 6,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
        {
            id: 7,
            image: './images/products/products-2.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 8,
            image: './images/products/products-4.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'rejected',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 9,
            image: './images/products/products-1.jpg',
            name: 'Macbook Pro 15inch',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Jun 27, 2017',
            status: 'active',
            location: 'Dhaka,Bangladesh',
            category: 'laptop',
        },
        {
            id: 10,
            image: './images/products/products-2.jpg',
            name: 'Study Table Combo',
            ad_id: 'ng3D5hAMHP',
            date_posted: 'Feb 12, 2017',
            status: 'pending',
            location: 'USA',
            category: 'cars',
        },
    ]
}